### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by Eredrim** [TheNewEconomy/TNE-Bukkit#101]
Hello, with the lastest version (0.0.4.2), I have this stack on server stopping.

> [13:36:25 WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'username' at row 1
[13:36:25 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3868)
[13:36:25 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[13:36:25 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[13:36:25 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[13:36:25 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
[13:36:25 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[13:36:25 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[13:36:25 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[13:36:25 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
[13:36:25 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[13:36:25 WARN]:        at com.github.tnerevival.core.db.MySQL.executePreparedUpdate(MySQL.java:128)
[13:36:25 WARN]:        at com.github.tnerevival.core.version.Alpha4_0.saveMySQL(Alpha4_0.java:635)
[13:36:25 WARN]:        at com.github.tnerevival.core.SaveManager.saveMySQL(SaveManager.java:294)
[13:36:25 WARN]:        at com.github.tnerevival.core.SaveManager.save(SaveManager.java:247)
[13:36:25 WARN]:        at com.github.tnerevival.TNE.onDisable(TNE.java:154)
[13:36:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294)
[13:36:25 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
[13:36:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[13:36:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[13:36:25 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.disablePlugins(CraftServer.java:341)
[13:36:25 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.stop(MinecraftServer.java:455)
[13:36:25 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:81)
[13:36:25 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
[13:36:25 WARN]:        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31)
[13:36:25 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:742)
[13:36:25 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[13:36:25 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[13:36:25 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[13:36:25 WARN]:        at java.lang.Thread.run(Unknown Source)

EDIT: Not only happens on server stopping, I've just seen the error after typing a /bal command

**Comment by creatorfromhell** [comment]
What plugins are you using?

**Comment by creatorfromhell** [comment]
Fixed in 983377ba7ff2edec9515b48b72572b60595232cd
