### ISSUE TITLE
converting FlatFile -> SQL

### ISSUE THREAD

**Issue by M9GLiquid** [TheNewEconomy/TNE-Bukkit#107]
Got error converting FlatFile -> SQL

```
[20:04:08] [Server thread/INFO]: [TheNewEconomy] Enabling TheNewEconomy v0.0.5.0
[20:04:08] [Thread-9/WARN]: [PermissionsEx] The updater could not find any files for the project id 31279
[20:04:08] [Server thread/INFO]: Unable to find JBDC File.
[20:04:08] [Server thread/WARN]: java.lang.ClassNotFoundException: org.h2.Driver
[20:04:08] [Server thread/WARN]:     at java.net.URLClassLoader.findClass(Unknown Source)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[20:04:08] [Server thread/WARN]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[20:04:08] [Server thread/WARN]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[20:04:08] [Server thread/WARN]:     at java.lang.Class.forName0(Native Method)
[20:04:08] [Server thread/WARN]:     at java.lang.Class.forName(Unknown Source)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.db.H2.connect(H2.java:53)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.db.H2.executeUpdate(H2.java:109)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.version.impl.Alpha5_0.createTables(Alpha5_0.java:1080)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.SaveManager.initiate(SaveManager.java:132)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.SaveManager.initialize(SaveManager.java:45)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.TNE.onEnable(TNE.java:97)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:04:08] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
[20:04:08] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539)
[20:04:08] [Server thread/WARN]:     at java.lang.Thread.run(Unknown Source)
[20:04:08] [Server thread/INFO]: Unable to find JBDC File.
[20:04:08] [Server thread/WARN]: java.lang.ClassNotFoundException: org.h2.Driver
[20:04:08] [Server thread/WARN]:     at java.net.URLClassLoader.findClass(Unknown Source)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[20:04:08] [Server thread/WARN]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[20:04:08] [Server thread/WARN]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[20:04:08] [Server thread/WARN]:     at java.lang.Class.forName0(Native Method)
[20:04:08] [Server thread/WARN]:     at java.lang.Class.forName(Unknown Source)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.db.H2.connect(H2.java:53)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.db.H2.connection(H2.java:67)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.db.H2.executeUpdate(H2.java:112)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.version.impl.Alpha5_0.createTables(Alpha5_0.java:1080)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.SaveManager.initiate(SaveManager.java:132)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.core.SaveManager.initialize(SaveManager.java:45)
[20:04:08] [Server thread/WARN]:     at com.github.tnerevival.TNE.onEnable(TNE.java:97)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:04:08] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:04:08] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
[20:04:08] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270)
[20:04:08] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539)
[20:04:08] [Server thread/WARN]:     at java.lang.Thread.run(Unknown Source)
[20:04:08] [Server thread/ERROR]: Error occurred while enabling TheNewEconomy v0.0.5.0 (Is it up to date?)
java.lang.NullPointerException
    at com.github.tnerevival.core.db.H2.executeUpdate(H2.java:112) ~[?:?]
    at com.github.tnerevival.core.version.impl.Alpha5_0.createTables(Alpha5_0.java:1080) ~[?:?]
    at com.github.tnerevival.core.SaveManager.initiate(SaveManager.java:132) ~[?:?]
    at com.github.tnerevival.core.SaveManager.initialize(SaveManager.java:45) ~[?:?]
    at com.github.tnerevival.TNE.onEnable(TNE.java:97) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-3ccadba-7f1a322]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-3ccadba-7f1a322]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-3ccadba-7f1a322]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-3ccadba-7f1a322]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-3ccadba-7f1a322]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot.jar:git-Spigot-3ccadba-7f1a322]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot.jar:git-Spigot-3ccadba-7f1a322]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot.jar:git-Spigot-3ccadba-7f1a322]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot.jar:git-Spigot-3ccadba-7f1a322]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot.jar:git-Spigot-3ccadba-7f1a322]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
```
I believe it was from me going from Flatfile -> SqlLite

```
# The New Economy v0.0.5.0
# Author: creatorfromhell
# License: AGPLv3
# If you would like to contribute to the plugin
# you can do so via Github at https://github.com/TheNewEconomy/TNE-Bukkit
Core:
  UUID: true
  Multiworld: true
  Metrics: true
  Debug: false
  Pins:
    Enabled: false
    Force: false
  Commands:
    PayShort: true
    BalanceShort: true
  Update:
    Check: true
    Notify: true
  Transactions:
    Track: true
    Format: M, d y
    Timezone: US/Eastern
  AutoSaver:
    Enabled: true
    Interval: 10000
  Currency:
    Default:
      Format: <symbol><major><decimal><minor><shorten>
      Balance: 200.0
      Default: true
      Conversion: 1.0
      Symbol: $
      Decimal: .
      ItemCurrency: false
      ItemMajor: GOLD_INGOT
      ItemMinor: IRON_INGOT
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Format: <symbol><major><decimal><minor><shorten>
    Conversion: 1.0
    Symbol: $
    Decimal: .
    ItemCurrency: false
    ItemMajor: GOLD_INGOT
    ItemMinor: IRON_INGOT
    MajorName:
      Single: Dollar
      Plural: Dollars
    MinorName:
      Single: Cent
      Plural: Cents
  Auctions:
    Enabled: true
    Cost: 10
    AllowWorld: true
    Multiple: true
    MaxMultiple: 5
    PersonalQueue: 3
    MaxQueue: 10
    MaxStart: 2000
    MinStart: 1
    MaxIncrement: 1000
    MinIncrement: 1
    MaxTime: 60
    MinTime: 30
    AntiSnipe: false
    SnipePeriod: 30
    SnipeTime: 20
    Announce: true
    Interval: 10
    Countdown: true
    CountdownTime: 10
  Shops:
    Enabled: true
    Cost: 10.0
    Max: 5
    Rows: 3
    Shoppers: 10
    Shares:
      Enabled: true
      Max: 3
  Signs:
    Bank:
      Enabled: true
      Place: 20.0
      Use: 20.0
    Shop:
      Enabled: true
      Place: 20.0
      Use: 20.0
  Death:
    Lose: false
    Bank:
      Drop: 0
      IncludeEmpty: true
      PlayerOnly: true
  Bank:
    Enabled: true
    Command: false
    NPC: false
    Connected: false
    Cost: 20.0
    Rows: 3
    Interest:
      Enabled: false
      Rate: 0.2
      Interval: 1800
  World:
    EnableChangeFee: false
    ChangeFee: 5.0
  Database:
    Type: SQLite
    Prefix: TNE
    Backup: true
    FlatFile:
      File: economy.tne
    MySQL:
      Host: localhost
      Port: 3306
      Database: TheNewEconomy
      User: user
      Password: password
    H2:
      File: Economy
    SQLite:
      File: economy.db
  Conversion:
    Convert: false
    Name: iConomy
    Format: MySQL
    Options:
      Host: localhost
      Port: 3306
      Database: sql_eco
      User: root
      Password: Password
  Balance: 200.0
  Shorten: true
```

Maybe have it so that if it doesn't work with the Database type selected it should automatically use flatfile so that it can still be used (as a backup) and ofcourse write out a error in console for the players to find

**Comment by creatorfromhell** [comment]
This is due to the H2 driver missing.(we don't use SQLite anymore)
