### ISSUE TITLE
Startup error with BiomeFinder

### ISSUE THREAD

**Issue by SlimeDog** [TheNewEconomy/TNE-Bukkit#108]
Spigot 1.11 latest pull, and the usual suspects: WE/WG, PEX, MV, etc, etc, all latest 1.11 pulls.

[19:23:10] [Server thread/INFO]: [BiomeFinder] Enabling BiomeFinder v1.2.2
[19:23:10] [Server thread/ERROR]: Error occurred while enabling BiomeFinder v1.2.2 (Is it up to date?)
java.lang.NullPointerException
        at com.github.tnerevival.core.api.TNEAPI.getCurrencyName(TNEAPI.java:254) ~[?:?]
        at com.github.tnerevival.core.api.TNEAPI.getCurrencyName(TNEAPI.java:250) ~[?:?]
        at com.github.tnerevival.core.TNEVaultEconomy.currencyNamePlural(TNEVaultEconomy.java:189) ~[?:?]
        at us.blockbox.biomefinder.BiomeSignHandler.<init>(BiomeSignHandler.java:34) ~[?:?]
        at us.blockbox.biomefinder.BiomeFinder.onEnable(BiomeFinder.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar-2016-11-24-0910:git-Spigot-31fef09-c3d951d]

**Comment by creatorfromhell** [comment]
What's your configuration file? (if you using worlds.yml please post that too).

**Comment by SlimeDog** [comment]
Here you go. Uploaded as .txt, since the uploader doesn't accept .yml files.

[config.yml.txt](https://github.com/TheNewEconomy/TNE-Bukkit/files/612525/config.yml.txt)
[worlds.yml.txt](https://github.com/TheNewEconomy/TNE-Bukkit/files/612526/worlds.yml.txt)

**Comment by creatorfromhell** [comment]
Did BiomeFinder get enabled before TNE? That could be the issue. I'm not sure the context of the situation, but the currency BiomeFinder is looking for does not exist. From your configurations, the only currency that exists is named "Default". IF you're attempting to look it up with any other name it'll throw the above error.

**Comment by SlimeDog** [comment]
Thanks. Shouldn't TNE (or any economy plugin) get loaded pretty early in the sequence. BiomeFinder (and other plugins) have no way of knowing if an economy plugin is on the menu. And there is nothing in _BiomeFinder/config.yml_ that mentions an economy.

**Comment by creatorfromhell** [comment]
It should, but it could just be BiomeFinder attempting to get a currency name that doesn't exist. Either way that's what the issue is(I'm not familiar with BiomeFinder).

**Comment by SlimeDog** [comment]
I have no idea what currencyName _BiomeFinder_ is looking for. There is no indication of a currency in the _BiomeFinder/config.yml_. Without _TNE_, _BiomeFinder_ produces no error, and finds _Essentials_ _Economy_. With _TNE_ installed, the log shows:
`[19:32:14] [Server thread/INFO]: [BiomeFinder] Loading BiomeFinder v1.2.2`
`...`
`[19:32:15] [Server thread/INFO]: [TheNewEconomy] Loading TheNewEconomy v0.0.5.0`
`...`
`[19:32:15] [Server thread/INFO]: [Essentials] Loading Essentials v2.0.1-b446`
`...`
`[19:32:15] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting`
`...`
`[19:32:19] [Server thread/INFO]: [BiomeFinder] Enabling BiomeFinder v1.2.2`
`[19:32:19] [Server thread/ERROR]: Error occurred while enabling BiomeFinder v1.2.2 (Is it up to date?)`
`...`
`... THE ERROR TRACE ...`
`...`
`[19:32:19] [Server thread/INFO]: [TheNewEconomy] Enabling TheNewEconomy v0.0.5.0`
`...`
`[19:32:20] [Server thread/INFO]: [Essentials] Enabling Essentials v2.0.1-b446`
`...`
`[19:32:20] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.`
`...`
`[19:32:20] [Server thread/INFO]: [Essentials] Payment method found (Vault - Economy: TheNewEconomy version: 1.5.6-b49)`
`...`
Without TNE, just elide the "TheNewEconomy" lines, and the _BiomeFinder_ error.

In any event, I understand the issue, and unless you have something more to discuss, I will close the ticket.

**Comment by creatorfromhell** [comment]
I have a few issues I'm working on atm, but I'll definitely be downloading BiomeFinder and looking into this more.

**Comment by SlimeDog** [comment]
Thanks. Interested to know the results.

**Comment by creatorfromhell** [comment]
Just as I suspected, BiomeFinder is getting enabled before TNE. I'm not sure if this is due to BiomdFinder's lack of depending on Vault or not. However, if you open the biomefinder jar with winzip(or any other of the millions of archive modifying softwares out there) and replace the plugin.yml with the attached one it'll work as intended(I added a dependency to TNE in it.(you'll have to rename it and remove the .txt extension)
[plugin.yml.txt](https://github.com/TheNewEconomy/TNE-Bukkit/files/614606/plugin.yml.txt)

**Comment by SlimeDog** [comment]
Thanks. I passed that on, to the developer. Hopefully...
