### ISSUE TITLE
Chestshop currency error and problem on selling

### ISSUE THREAD

**Issue by Eredrim** [TheNewEconomy/TNE-Bukkit#110]
Hello,

I have a problem with chestshop. Currently I can buy without visible problem in game but the console was flooded by this exception : 

```
[15:54:01] [Server thread/ERROR]: Could not pass event CurrencyAddEvent to ChestShop v3.8.14
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:404) [ChestShop.jar:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.EconomicModule.onBuyTransaction(EconomicModule.java:28) [ChestShop.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:106) [ChestShop.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.account.IDFinder.getID(IDFinder.java:64) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsAdd(TNEAPI.java:187) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.depositPlayer(TNEVaultEconomy.java:103) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Economy.Plugins.VaultListener.onCurrencyAdd(VaultListener.java:133) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	... 36 more
```

Other problem, when I sell something for $1, I get $1000 and these two exceptions : 

```
[15:54:35] [Server thread/ERROR]: Could not pass event CurrencyCheckEvent to ChestShop v3.8.14
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:404) [ChestShop.jar:?]
	at com.Acrobot.ChestShop.Listeners.PreTransaction.PartialTransactionModule.onPreSellTransaction(PartialTransactionModule.java:110) [ChestShop.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:101) [ChestShop.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:110) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:821) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.account.IDFinder.getID(IDFinder.java:64) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsHas(TNEAPI.java:202) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.has(TNEVaultEconomy.java:124) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Economy.Plugins.VaultListener.onCurrencyCheck(VaultListener.java:91) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	... 37 more
```

```
[15:54:35] [Server thread/ERROR]: Could not pass event CurrencySubtractEvent to ChestShop v3.8.14
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:404) [ChestShop.jar:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.EconomicModule.onSellTransaction(EconomicModule.java:43) [ChestShop.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:106) [ChestShop.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:110) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:821) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.account.IDFinder.getID(IDFinder.java:64) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsHas(TNEAPI.java:202) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.has(TNEVaultEconomy.java:124) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.withdrawPlayer(TNEVaultEconomy.java:180) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Economy.Plugins.VaultListener.onCurrencySubtraction(VaultListener.java:148) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11-pre.jar:git-Spigot-f950f8e-eb6c1bf]
	... 37 more
```

**Comment by creatorfromhell** [comment]
Will have to run some local tests, but odds are it's not going to be present in 5.1 since it is due to API issues, and the API has mostly been redone.

**Comment by creatorfromhell** [comment]
Quick update, I haven't been able to reproduce this error. I'm not sure how your configurations look, but so far on my end everything works as intended.

**Comment by Eredrim** [comment]
Can you retry with this version of chestshop https://github.com/dmulloy2/ChestShop-3 ? It is the most active fork of the official version and the version I use, the official one being no longer developed.

**Comment by creatorfromhell** [comment]
If they have an available download I'll give it a shot.

**Comment by creatorfromhell** [comment]
http://prntscr.com/dftsm8 Still working fine for me.

**Comment by Eredrim** [comment]
I confirm, it works fine with the last version (cf. #113)
