### ISSUE TITLE
Problem with cents

### ISSUE THREAD

**Issue by Eredrim** [TheNewEconomy/TNE-Bukkit#113]
When I release transactions with hundredths but without tenth, hundredths become tenths. For example, I pay $1.05 to player2, I am debited of $1.5 and player2 is credited of $1.5.

**Comment by creatorfromhell** [comment]
http://prntscr.com/dfgajv It seems to be working fine for me now.
[TNE.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/630085/TNE.zip)
Try the attached file.

**Comment by Eredrim** [comment]
For unknown reasons, I can't launch the plugin on the latest spigot 1.11 version (git-Spigot-f950f8e-a710176). You can see the error below : 
```
[23:49:54 ERROR]: Error occurred while enabling TheNewEconomy v0.0.5.1 (Is it up to date?)
java.lang.NullPointerException
        at com.github.tnerevival.core.version.impl.Alpha5_0.saveAccount(Alpha5_0.java:115) ~[?:?]
        at com.github.tnerevival.listeners.collections.AccountsListener.add(AccountsListener.java:31) ~[?:?]
        at com.github.tnerevival.core.collection.EventMap.put(EventMap.java:46) ~[?:?]
        at com.github.tnerevival.core.version.impl.Alpha5_0.loadMySQL(Alpha5_0.java:671) ~[?:?]
        at com.github.tnerevival.core.SaveManager.loadMySQL(SaveManager.java:294) ~[?:?]
        at com.github.tnerevival.core.SaveManager.load(SaveManager.java:239) ~[?:?]
        at com.github.tnerevival.core.SaveManager.initialize(SaveManager.java:50) ~[?:?]
        at com.github.tnerevival.TNE.onEnable(TNE.java:96) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-f950f8e-a710176]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
```

**Comment by creatorfromhell** [comment]
What version of TNE are your running?

**Comment by creatorfromhell** [comment]
Try this build.
[TNE.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/632629/TNE.zip)

**Comment by Eredrim** [comment]
It works but all the commands which affects accounts (/money <give|take|set> and /pay) modify the essentials account amount instead of the TNE account.

**Comment by creatorfromhell** [comment]
I haven't encountered this issue as of yet. There should be no interference from Essentials. I have been running essentials on my test server for around six months now, and haven't had this issue.
