### ISSUE TITLE
Error in used ItemCurrency

### ISSUE THREAD

**Issue by skay1994** [TheNewEconomy/TNE-Bukkit#116]
```java
[12:23:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin TheNewEconomy v0.0.5.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-44216f1]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-44216f1]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:624) ~[craftbukkit.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1298) [craftbukkit.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1158) [craftbukkit.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-44216f1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:679) [craftbukkit.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635) [craftbukkit.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539) [craftbukkit.jar:git-Bukkit-44216f1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.tnerevival.core.material.MaterialHelper
	at com.github.tnerevival.utils.AccountUtils.getBalance(AccountUtils.java:54) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getFunds(AccountUtils.java:125) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.getBalance(TNEAPI.java:234) ~[?:?]
	at com.github.tnerevival.commands.money.MoneyBalanceCommand.execute(MoneyBalanceCommand.java:58) ~[?:?]
	at com.github.tnerevival.commands.money.MoneyCommand.execute(MoneyCommand.java:62) ~[?:?]
	at com.github.tnerevival.TNE.onCommand(TNE.java:169) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-44216f1]
	... 15 more
```

**Comment by creatorfromhell** [comment]
This is most likely due to MaterialHelper containing 1.10+ blocks, I'll have to add some checks to see what MC version servers are using.
