### ISSUE TITLE
FATAL ERROR: null

### ISSUE THREAD

**Issue by TomberWolf** [TheNewEconomy/TNE-Bukkit#136]
On Thermos Server 1.7.10:

`[10:27:42] [Server thread/INFO]: Testplayer issued server command: /money
[10:27:42] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin TheNewEconomy v0.0.5.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1211) [nh.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.chat(CraftPlayer.java:274) [CraftPlayer.class:1.7.10-1614.58]
	at it.mri.mycommand.execute.types.AliasType.ExecuteAliasForPlayer(AliasType.java:48) [MyCommand%205.3.4.jar:?]
	at it.mri.mycommand.execute.DispatchCommands.ExecuteMyCommandCommands(DispatchCommands.java:352) [MyCommand%205.3.4.jar:?]
	at it.mri.mycommand.listener.PreprocessEvent.onPlayerCommandPreprocess(PreprocessEvent.java:240) [MyCommand%205.3.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) [JavaPluginLoader$1.class:1.7.10-1614.58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1348) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchFieldError: SLIME_BLOCK
	at com.github.tnerevival.core.material.MaterialHelper.<clinit>(MaterialHelper.java:179) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getBalance(AccountUtils.java:103) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getFunds(AccountUtils.java:171) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.getBalance(TNEAPI.java:196) ~[?:?]
	at com.github.tnerevival.commands.money.MoneyBalanceCommand.execute(MoneyBalanceCommand.java:58) ~[?:?]
	at com.github.tnerevival.commands.money.MoneyCommand.execute(MoneyCommand.java:62) ~[?:?]
	at com.github.tnerevival.TNE.onCommand(TNE.java:178) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
	... 27 more`

And something similar:

`[10:27:47] [Server thread/INFO]: Testplayer issued server command: /money
[10:27:47] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin TheNewEconomy v0.0.5.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.tnerevival.core.material.MaterialHelper
	at com.github.tnerevival.utils.AccountUtils.getBalance(AccountUtils.java:103) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.getFunds(AccountUtils.java:171) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.getBalance(TNEAPI.java:196) ~[?:?]
	at com.github.tnerevival.commands.money.MoneyBalanceCommand.execute(MoneyBalanceCommand.java:58) ~[?:?]
	at com.github.tnerevival.commands.money.MoneyCommand.execute(MoneyCommand.java:62) ~[?:?]
	at com.github.tnerevival.TNE.onCommand(TNE.java:178) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
	... 13 more`

**Comment by creatorfromhell** [comment]
Both of your errors are related to this issue, so I'm going to close the other one. However, the jar in this zip should fix the issue.
[TNE.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/776949/TNE.zip)

**Comment by creatorfromhell** [comment]
No problem. You're welcome.
