### ISSUE TITLE
Unexpected exception for reloading all

### ISSUE THREAD

**Issue by TomberWolf** [TheNewEconomy/TNE-Bukkit#138]
Uhm... I hope it's okay to report as many issues as I find without being annoying.

The command **/tne reload all** results in an error:

`[13:54:14] [Server thread/WARN]: Unexpected exception while parsing console command "theneweconomy reload all"
org.bukkit.command.CommandException: Unhandled exception executing command 'theneweconomy' in plugin TheNewEconomy v0.0.5.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:720) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:474) [lt.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:433) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.core.configurations.ConfigurationManager.load(ConfigurationManager.java:94) ~[?:?]
	at com.github.tnerevival.utils.MISCUtils.reloadConfigPlayers(MISCUtils.java:267) ~[?:?]
	at com.github.tnerevival.utils.MISCUtils.reloadConfigurations(MISCUtils.java:207) ~[?:?]
	at com.github.tnerevival.commands.admin.AdminReloadCommand.execute(AdminReloadCommand.java:46) ~[?:?]
	at com.github.tnerevival.commands.TNECommand.execute(TNECommand.java:203) ~[?:?]
	at com.github.tnerevival.TNE.onCommand(TNE.java:178) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
	... 8 more`

**Comment by creatorfromhell** [comment]
This seems to have fixed the issue.
[TNE.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/777118/TNE.zip)

**Comment by TomberWolf** [comment]
It does. Thanks again.
