### ISSUE TITLE
Could not pass event InventoryCloseEvent

### ISSUE THREAD

**Issue by TomberWolf** [TheNewEconomy/TNE-Bukkit#141]
An issue I didn't seen befor on our Thermos 1.7.10 server:

`[17:13:56] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to TheNewEconomy v0.0.5.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:910) [CraftEventFactory.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147356_a(NetHandlerPlayServer.java:1693) [nh.class:?]
	at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(C0DPacketCloseWindow.java:27) [iy.class:?]
	at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(C0DPacketCloseWindow.java:42) [iy.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_121]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_121]
	at com.github.tnerevival.core.inventory.TNEInventory.onClose(TNEInventory.java:239) ~[?:?]
	at com.github.tnerevival.core.inventory.impl.GenericInventory.onClose(GenericInventory.java:44) ~[?:?]
	at com.github.tnerevival.listeners.InventoryListener.onInventoryClose(InventoryListener.java:85) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	... 14 more
`

**Comment by creatorfromhell** [comment]
This is a known issue with 5.1, and will be fixed in 5.2. Thanks for the report though. ^^
