### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by sidekixmc** [TheNewEconomy/TNE-Bukkit#166]
I get this error when killing monsters

```
[18:58:55 ERROR]: Could not pass event EntityDeathEvent to TheNewEconomy v0.0.5.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1108) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.EntityZombie.die(EntityZombie.java:429) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:950) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:999) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1296) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1609) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-pre6.jar:git-Spigot-ac83d69-fe3ca95]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
```

**Comment by creatorfromhell** [comment]
Closed this as it does not follow the proper issue report format, nor does it even come close since it only provides half of the stacktrace.
