### ISSUE TITLE
TNE Bug, money reset for some

### ISSUE THREAD

**Issue by FenhCS** [TheNewEconomy/TNE-Bukkit#195]
[12:21:13] [Server thread/WARN]: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'trans_oldBalance' at row 1
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971)
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[12:21:13] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.db.SQLDatabase.executePreparedUpdate(SQLDatabase.java:79)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.version.impl.Alpha5_5.saveTransaction(Alpha5_5.java:280)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.listeners.collections.TransactionsListener.add(TransactionsListener.java:54)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.collection.EventList.add(EventList.java:87)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.transaction.TransactionHistory.add(TransactionHistory.java:44)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.transaction.TransactionHistory.add(TransactionHistory.java:40)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.TransactionManager.add(TransactionManager.java:80)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.TransactionManager.add(TransactionManager.java:65)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.TransactionManager.add(TransactionManager.java:39)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.transaction.Transaction.perform(Transaction.java:56)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:417)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:412)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.api.TNEAPI.fundsRemove(TNEAPI.java:152)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.api.TNEAPI.fundsRemove(TNEAPI.java:141)
[12:21:13] [Server thread/WARN]: at com.github.tnerevival.core.TNEVaultEconomy.withdrawPlayer(TNEVaultEconomy.java:423)
[12:21:13] [Server thread/WARN]: at com.palmergames.bukkit.towny.TownyEconomyHandler.subtract(TownyEconomyHandler.java:310)
[12:21:13] [Server thread/WARN]: at com.palmergames.bukkit.towny.object.TownyEconomyObject._pay(TownyEconomyObject.java:55)
[12:21:13] [Server thread/WARN]: at com.palmergames.bukkit.towny.object.TownyEconomyObject._payTo(TownyEconomyObject.java:106)
[12:21:13] [Server thread/WARN]: at com.palmergames.bukkit.towny.object.TownyEconomyObject.payTo(TownyEconomyObject.java:98)
[12:21:13] [Server thread/WARN]: at com.palmergames.bukkit.towny.command.TownCommand.townDeposit(TownCommand.java:2629)
[12:21:13] [Server thread/WARN]: at com.palmergames.bukkit.towny.command.TownCommand.parseTownCommand(TownCommand.java:180)
[12:21:13] [Server thread/WARN]: at com.palmergames.bukkit.towny.command.TownCommand.onCommand(TownCommand.java:91)
[12:21:13] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:21:13] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:21:13] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:21:13] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:21:13] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[12:21:13] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[12:21:13] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by creatorfromhell** [comment]
All pre-beta 1 issues will now be getting closed as we near the end of beta testing.
