### ISSUE TITLE
/money take ...

### ISSUE THREAD

**Issue by Someone-NEW** [TheNewEconomy/TNE-Bukkit#197]
Hello will be cool when you can fix many bugs in this plugin, for example here i have no working /money take org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin TheNewEconomy v0.0.5.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:640) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at me.clip.deluxemenus.DeluxeMenusConfig$1.onClick(DeluxeMenusConfig.java:1514) ~[?:?]
        at me.clip.deluxemenus.PlayerListener.onClick(PlayerListener.java:159) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor222.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        ... 15 more
Caused by: java.lang.NullPointerException
        at com.github.tnerevival.account.IDFinder.getID(IDFinder.java:109) ~[?:?]
        at com.github.tnerevival.commands.money.MoneyTakeCommand.execute(MoneyTakeCommand.java:83) ~[?:?]
        at com.github.tnerevival.commands.TNECommand.execute(TNECommand.java:209) ~[?:?]
        at com.github.tnerevival.commands.money.MoneyCommand.execute(MoneyCommand.java:80) ~[?:?]
        at com.github.tnerevival.TNE.onCommand(TNE.java:196) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:640) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        at me.clip.deluxemenus.DeluxeMenusConfig$1.onClick(DeluxeMenusConfig.java:1514) ~[?:?]
        at me.clip.deluxemenus.PlayerListener.onClick(PlayerListener.java:159) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor222.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-596221b-b1b9ab0]
        ... 15 more

**Comment by creatorfromhell** [comment]
Let's start with this report doesn't follow the correct format, and as for the bugs, TNE is currently undergoing a recode for modularity and stability.

**Comment by Someone-NEW** [comment]
Than ignore it lool

**Comment by creatorfromhell** [comment]
All pre-beta 1 issues will now be getting closed as we near the end of beta testing.
