### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [TheNewEconomy/TNE-Bukkit#198]
logs
```
[11:26:40] [Server thread/INFO]: [TheNewEconomy] Enabling TheNewEconomy v0.0.5.5
[11:26:41] [Server thread/WARN]: java.net.ConnectException: Połączenie odrzucone (Connection refused)
[11:26:41] [Server thread/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[11:26:41] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[11:26:41] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[11:26:41] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[11:26:41] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[11:26:41] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[11:26:41] [Server thread/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[11:26:41] [Server thread/WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[11:26:41] [Server thread/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[11:26:41] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[11:26:41] [Server thread/WARN]: 	at java.net.URL.openStream(URL.java:1045)
[11:26:41] [Server thread/WARN]: 	at com.github.tnerevival.core.UpdateChecker.getLatestBuild(UpdateChecker.java:22)
[11:26:41] [Server thread/WARN]: 	at com.github.tnerevival.core.UpdateChecker.<init>(UpdateChecker.java:14)
[11:26:41] [Server thread/WARN]: 	at com.github.tnerevival.TNE.onEnable(TNE.java:93)
[11:26:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:26:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:26:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[11:26:41] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[11:26:41] [Server thread/WARN]: 	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[11:26:41] [Server thread/WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[11:26:41] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:26:41] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[11:26:41] [Server thread/WARN]: 	at gyurix.commands.CustomCommandMap.dispatch(CustomCommandMap.java:89)
[11:26:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672)
[11:26:41] [Server thread/WARN]: 	at github.scarsz.discordsrv.listeners.DiscordConsoleListener.lambda$onGuildMessageReceived$0(DiscordConsoleListener.java:93)
[11:26:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[11:26:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[11:26:41] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
[11:26:41] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[11:26:41] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[11:26:41] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[11:26:41] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

timings
https://timings.aikar.co/?id=bd3761a9f57445e08602300f8032ec89#plugins

**Comment by creatorfromhell** [comment]
This is due to my personal site being down in the event of switching servers. It doesn't have any side affect that is server-breaking, just no update checking.
