### ISSUE TITLE
MySQLNonTransientConnectionException

### ISSUE THREAD

**Issue by marcotaub** [TheNewEconomy/TNE-Bukkit#221]
Spigot 1.12.2, Plugins: BungeeTabListPlus, ChestCommands,dynmap,EssentialsX*, FAWE, HolographicDisplays, Jobs, LuckyBlockSuper, Multiverse, MyCommand, NetworkmanagerBridge, NCP, PEX, PLOT2DYNMAP, Plugman, RedClock, Safetrade, Statz, TNE, Vault, WebSender, Worldedit, worldguard

Ab und an bekomme ich diesen Fehler in der Console (Scheint nicht so als würde es das Spielgeschehen beeinflussen):

**[13:22:14] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
[13:22:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:22:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:22:14] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:22:14] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4071)
[13:22:14] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4040)
[13:22:14] [Server thread/WARN]: 	at com.github.tnerevival.core.db.SQLDatabase.executePreparedQuery(SQLDatabase.java:50)
[13:22:14] [Server thread/WARN]: 	at net.tnemc.mysql.MySQLProvider.loadAccount(MySQLProvider.java:349)
[13:22:14] [Server thread/WARN]: 	at net.tnemc.core.listeners.collections.AccountListener.get(AccountListener.java:43)
[13:22:14] [Server thread/WARN]: 	at com.github.tnerevival.core.collection.EventMap.get(EventMap.java:52)
[13:22:14] [Server thread/WARN]: 	at com.github.tnerevival.core.collection.EventMap.containsKey(EventMap.java:110)
[13:22:14] [Server thread/WARN]: 	at net.tnemc.core.common.EconomyManager.exists(EconomyManager.java:64)
[13:22:14] [Server thread/WARN]: 	at net.tnemc.core.common.EconomyManager.getAccount(EconomyManager.java:73)
[13:22:14] [Server thread/WARN]: 	at net.tnemc.core.listeners.ConnectionListener.onTeleport(ConnectionListener.java:119)
[13:22:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:22:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:22:14] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:22:14] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:22:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[13:22:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:22:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[13:22:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[13:22:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:510)
[13:22:14] [Server thread/WARN]: 	at com.plotsquared.bukkit.object.BukkitPlayer.teleport(BukkitPlayer.java:168)
[13:22:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.object.Plot.teleportPlayer(Plot.java:2614)
[13:22:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Visit$1.run(Visit.java:150)
[13:22:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:176)
[13:22:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:135)
[13:22:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Visit.execute(Visit.java:147)
[13:22:14] [Server thread/WARN]: 	at com.plotsquared.general.commands.Command.execute(Command.java:337)
[13:22:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:260)
[13:22:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:135)
[13:22:14] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[13:22:14] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:22:14] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[13:22:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:22:14] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:22:14] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[13:22:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[13:22:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)**
 

Ich hoffe du kannst damit was anfangen!

**Comment by creatorfromhell** [comment]
Not too much information to go off of here, but I'll remember this if it pops up for another user.

Thanks,
   creatorfromhell
