### ISSUE TITLE
MYSQL config broken in 0.1.1.2

### ISSUE THREAD

**Issue by Owizardo** [TheNewEconomy/TNE-Bukkit#244]
I am getting the following error when trying to modify the config to add the SQL settings.

> [03:25:10 INFO]: [TheNewEconomy] Enabling TheNewEconomy v0.1.1.2
> [03:25:10 INFO]: [TheNewEconomy] Found module: Conversion version: 0.1.0
> [03:25:10 INFO]: [TheNewEconomy] Found module: MySQL version: 0.1.0
> [03:25:10 INFO]: [TheNewEconomy] Found module: H2 version: 0.1.0
> [03:25:10 INFO]: [TheNewEconomy] Found module: Mobs version: 0.1.0
> [03:25:10 INFO]: MySQL Module loaded!
> [03:25:10 INFO]: Mobs Module loaded!
> [03:25:10 INFO]: H2 Module loaded!
> [03:25:10 INFO]: [TheNewEconomy] Conversion Module loaded!
> [03:25:11 ERROR]: Error occurred while enabling TheNewEconomy v0.1.1.2 (Is it up to date?)
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
at net.tnemc.core.common.configurations.ConfigurationManager.getString(ConfigurationManager.java:168) ~[?:?]
at net.tnemc.core.common.configurations.ConfigurationManager.getString(ConfigurationManager.java:148) ~[?:?]
at net.tnemc.core.TNE.onEnable(TNE.java:312) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-2440e18-4c219e2]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [server.jar:git-Spigot-2440e18-4c219e2]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-2440e18-4c219e2]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [server.jar:git-Spigot-2440e18-4c219e2]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [server.jar:git-Spigot-2440e18-4c219e2]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:582) [server.jar:git-Spigot-2440e18-4c219e2]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:545) [server.jar:git-Spigot-2440e18-4c219e2]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:423) [server.jar:git-Spigot-2440e18-4c219e2]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [server.jar:git-Spigot-2440e18-4c219e2]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [server.jar:git-Spigot-2440e18-4c219e2]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Owizardo** [comment]
Here is my config

  Database:
    Type: MySQL
    Prefix: TNE
    Backup: true
    File: Economy
    MySQL:
      Host: localhost
      Port: 3306
      Database: Minecraft-PROD-DB
      User: Owizardo
      Password: superduperscretpassword

**Comment by creatorfromhell** [comment]
this doesnt use the correct format, please use the correct format that is auto populated by github whwn you start a new issue
