### ISSUE TITLE
MySQL and Faction unable to Deposit

### ISSUE THREAD

**Issue by lueljohn** [TheNewEconomy/TNE-Bukkit#28]
Good day sir!

Yesterday I talked about an issue of the Factions plugin causing internal error. Now, I can't deposit any cash on the Faction's Econ bank. What's the solution for it?

And also, the plugin doesn't comply or connect to the MySQL server.
Here's the error log:

[03:59:17] [Server thread/INFO]: [TheNewEconomy] Enabling TheNewEconomy v0.0.2.3
[03:59:17] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection https://creatorfromhell.com/tne/tnebuild.txt in main server thread
[03:59:17] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection socket://creatorfromhell.com:443 in main server thread
[03:59:18] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection socket://localhost:3306 in main server thread
[03:59:18] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection socket://localhost:3306 in main server thread
[03:59:18] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
[03:59:18] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:59:18] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[03:59:18] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:59:18] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1662)
[03:59:18] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1581)
[03:59:18] [Server thread/WARN]: 	at com.github.tnerevival.core.SaveManager.createMySQLTables(SaveManager.java:823)
[03:59:18] [Server thread/WARN]: 	at com.github.tnerevival.core.SaveManager.initiate(SaveManager.java:117)
[03:59:18] [Server thread/WARN]: 	at com.github.tnerevival.core.SaveManager.<init>(SaveManager.java:49)
[03:59:18] [Server thread/WARN]: 	at com.github.tnerevival.TNE.onEnable(TNE.java:84)
[03:59:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[03:59:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[03:59:18] [Server thread/WARN]: 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145)
[03:59:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:59:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[03:59:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[03:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[03:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[03:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[03:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[03:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[03:59:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

Here's the photo of the Faction Deposit problem:
http://i.imgur.com/Ap56Mmd.jpg

I hope for a fast reply. Thank you! <3

**Comment by lueljohn** [comment]
I already fixed it by disabling the Bank function.

Now the problem is whenever I restart the server, my balance resets back to default money.
What should I do?

**Comment by lueljohn** [comment]
Here's another error:

21.10 05:26:21 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
21.10 05:26:21 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO at com.github.tnerevival.worker.SaveWorker.run(SaveWorker.java:17) ~[?:?]
21.10 05:26:21 [Server] INFO at com.github.tnerevival.core.SaveManager.save(SaveManager.java:261) ~[?:?]
21.10 05:26:21 [Server] INFO at com.github.tnerevival.core.SaveManager.saveSQLite(SaveManager.java:776) ~[?:?]
21.10 05:26:21 [Server] INFO at org.sqlite.Conn.prepareStatement(Conn.java:383) ~[craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO at org.sqlite.Conn.prepareStatement(Conn.java:399) ~[craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO at org.sqlite.Conn.prepareStatement(Conn.java:404) ~[craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO at org.sqlite.PrepStmt.<init>(PrepStmt.java:42) ~[craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
21.10 05:26:21 [Server] INFO java.lang.NullPointerException
21.10 05:26:21 [Server] WARN Task #44 for TheNewEconomy v0.0.2.3 generated an exception

**Comment by creatorfromhell** [comment]
Let's take this one error at a time.. 

Firstly, from the picture you sent, it appears that you don't have enough money to deposit into the faction's bank as the balance comes from cash on you, and not from your bank(this is due to the factions plugin only checking the player's balance and not bank balance).

Issues two and three I'll still need to look into, but should be easy fixes. Do you remember what you were doing when errors two and three popped up? I need to recreate them.

**Comment by lueljohn** [comment]
The errors are committed by the database file. Not enough money though is not the problem since I had 500 Pesos on the bank. I deposited it on the bank. Same thing happened when I removed the bank. It keeps asking me that I don't have that enough cash.

The account keeps getting reset every time the server restarts and commits the database error log on the console.

**Comment by creatorfromhell** [comment]
I didn't forget/ignore these errors, I've just been busy with work. I'm off tomorrow so I'll look into them more then. For now, I suggest using FlatFile for data storage.

**Comment by lueljohn** [comment]
After fixing it, please tell me how to convert the Flatfile to SQLite or MySQL.
Thank you :)

**Comment by creatorfromhell** [comment]
Note to self: this should be fixed with issue #18

**Comment by creatorfromhell** [comment]
Should be fixed with the next commit which is 75% complete at this time...I'll push it sometime tonight currently I've reworked flatfile, and SQLite.

**Comment by creatorfromhell** [comment]
Should be fixed in Alpha 2.4 https://www.spigotmc.org/resources/the-new-economy.7805/update?update=53941
