### ISSUE TITLE
1.14 doesn't support calling non-async events from another thread

### ISSUE THREAD

**Issue by rmb938** [TheNewEconomy/TNE-Bukkit#282]
#### What is the issue/bug you're experiencing?

`/balance` and `/money` commands don't work

#### How can the issue be reproduced?

1. Use 1.14 spigot
1. Install 1.1.7 of TNE
1. Join the server and run `/balance`

#### TNE version? 
`1.1.7`

#### TNE build?(/tne build) 
`3Beta115`
#### Modules Loaded?(exact version number) 
`H2`
#### Spigot/Bukkit version? 
`git-Spigot-1eece4f-84400e6 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
`
#### Is your server run in online mode?

Yes

#### The exact command you ran w/ arguments?

`/balance`

#### Exception Logs

```
[11:52:05] [Server thread/INFO]: rmb938 issued server command: /balance
[11:52:05] [Craft Scheduler Thread - 2/WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.7 generated an exception while executing task 54
java.lang.IllegalStateException: TNEPreTransaction cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-1eece4f-84400e6]
	at net.tnemc.core.common.TransactionManager.perform(TransactionManager.java:130) ~[?:?]
	at net.tnemc.core.commands.money.MoneyBalanceCommand.lambda$execute$1(MoneyBalanceCommand.java:107) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-1eece4f-84400e6]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-1eece4f-84400e6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[11:52:54] [Server thread/INFO]: rmb938 issued server command: /money
[11:52:54] [Craft Scheduler Thread - 2/WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.7 generated an exception while executing task 55
java.lang.IllegalStateException: TNEPreTransaction cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-1eece4f-84400e6]
	at net.tnemc.core.common.TransactionManager.perform(TransactionManager.java:130) ~[?:?]
	at net.tnemc.core.commands.money.MoneyBalanceCommand.lambda$execute$1(MoneyBalanceCommand.java:107) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-1eece4f-84400e6]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-1eece4f-84400e6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

All commands and chat is async so if you want to continue to use these events you need to set the async param in their constructor. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/Event.html#Event-boolean-

See https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/SimplePluginManager.java#490

**Comment by creatorfromhell** [comment]
There's no TNE build out for 1.14.
