### ISSUE TITLE
IncompatibleClassChangeError, plugin disables itself

### ISSUE THREAD

**Issue by jstnf** [TheNewEconomy/TNE-Bukkit#289]
#### What is the issue/bug you're experiencing?
The plugin encounters an IncompatibleClassChangeError during loading.
In Spigot, the plugin continues despite the error. In Paper, it completely disables itself.
If this is purely setup related and will solve itself once the plugin is setup, then please disregard. It's just something that I've ran into while setting up my server.
Stack trace:
```
[02:57:19 ERROR]: Error occurred while enabling TheNewEconomy v0.1.1.8 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Expecting non-static method com.github.tnerevival.core.db.sql.H2.getDataSource()Lcom/zaxxer/hikari/HikariDataSource;
        at net.tnemc.h2.H2Provider.first(H2Provider.java:89) ~[?:?]
        at net.tnemc.core.common.data.TNESaveManager.initialize(TNESaveManager.java:38) ~[?:?]
        at net.tnemc.core.TNE.onEnable(TNE.java:320) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f09662d-9ead700]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Create a fresh server
Download latest version of TNE from spigotmc
Place in plugins and try running server
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.8, no
#### TNE build?(/tne build), and whether or not you've made modification to it.
17Beta118
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
H2, Mobs, Signs
#### Spigot/Bukkit version?
Used Paper and Spigot server jars:
Paper: `git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`
Spigot: `CraftBukkit version git-Spigot-f09662d-9ead700 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
N/A
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
Default config.yml
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/gKJTvQZTW6/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
N/A

**Comment by creatorfromhell** [comment]
You have an invalid h3 module  please use the one from the 0.1.1.8 zip

**Comment by jstnf** [comment]
I will try this later when I get the chance.

cheers
