### ISSUE TITLE
Getting errors when running any commands

### ISSUE THREAD

**Issue by FunkyJamma** [TheNewEconomy/TNE-Bukkit#290]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What is the issue/bug you're experiencing?
      at com.github.tnerevival.core.collection.EventMap.get(EventMap.java:52) ~[?:?]
        at com.github.tnerevival.core.collection.EventMap.containsKey(EventMap.java:110) ~[?:?]
        at net.tnemc.core.common.EconomyManager.exists(EconomyManager.java:91) ~[?:?]
        at net.tnemc.core.common.EconomyManager.getAccount(EconomyManager.java:100) ~[?:?]
        at net.tnemc.core.common.configurations.MessageConfigurations.getValue(MessageConfigurations.java:83) ~[?:?]
        at net.tnemc.core.common.configurations.ConfigurationManager.getValue(ConfigurationManager.java:110) ~[?:?]
        at net.tnemc.core.common.configurations.ConfigurationManager.getConfiguration(ConfigurationManager.java:185) ~[?:?]
        at net.tnemc.core.common.api.TNEAPI.getConfiguration(TNEAPI.java:831) ~[?:?]
        at net.tnemc.core.common.api.TNEAPI.getString(TNEAPI.java:777) ~[?:?]
        at net.tnemc.core.common.Message.format(Message.java:117) ~[?:?]
        at net.tnemc.core.common.Message.translate(Message.java:109) ~[?:?]
        at net.tnemc.core.common.Message.translate(Message.java:104) ~[?:?]
        at net.tnemc.core.commands.TNECommand.execute(TNECommand.java:235) ~[?:?]
        at net.tnemc.core.commands.money.MoneyCommand.execute(MoneyCommand.java:116) ~[?:?]
        at net.tnemc.core.TNE.customCommand(TNE.java:556) ~[?:?]
        at net.tnemc.core.TNE.onCommand(TNE.java:545) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-fcb9f90]
        ... 17 more

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
typing in any commands.
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.8 no
#### Spigot/Bukkit version?
1.14.1
#### Is your server run in online mode?
yes
#### The exact command you ran w/ arguments?
this happens on any command

**Comment by creatorfromhell** [comment]
Looks like your missing the H2/MySQL Module. Please follow the installation instructions posted on the spigot home page.
