### ISSUE TITLE
Faction Issue with Economy Pt. 2

### ISSUE THREAD

**Issue by lueljohn** [TheNewEconomy/TNE-Bukkit#35]
Good day!

Here's another issue with the Factions Plugin when I claim a territory.
What should I do?

[00:00:21] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection https://api.mojang.com/users/profiles/minecraft/PogiAkoSobra in main server thread
[00:00:21] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection socket://api.mojang.com:443 in main server thread
[00:00:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f money deposit 1000' in com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand(f)
	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:99) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_85]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_85]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.core.api.MojangAPI.getPlayerUUID(MojangAPI.java:21) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.getPlayerID(TNEAPI.java:163) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.accountExists(TNEAPI.java:22) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.hasAccount(TNEVaultEconomy.java:294) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.ensureExists(MoneyMixinVault.java:201) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.get(MoneyMixinVault.java:134) ~[?:?]
	at com.massivecraft.massivecore.money.Money.get(Money.java:115) ~[?:?]
	at com.massivecraft.factions.integration.Econ.transferMoney(Econ.java:131) ~[?:?]
	at com.massivecraft.factions.integration.Econ.transferMoney(Econ.java:101) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsMoneyDeposit.perform(CmdFactionsMoneyDeposit.java:49) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:617) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:596) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:596) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:649) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61) ~[?:?]
	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
	... 14 more

**Comment by lueljohn** [comment]
Here's another one (When creating a faction)

[01:05:22] [Server thread/INFO]: CrazyCakeZ issued server command: /f create RookZ
[01:05:22] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection https://api.mojang.com/users/profiles/minecraft/CrazyCakeZ in main server thread
[01:05:22] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection socket://api.mojang.com:443 in main server thread
[01:05:22] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection https://api.mojang.com/users/profiles/minecraft/CrazyCakeZ in main server thread
[01:05:22] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection https://api.mojang.com/users/profiles/minecraft/CrazyCakeZ in main server thread
[01:05:22] [Server thread/INFO]: [Factions 2.8.2] Non existing factionId 8e544ea0-5d72-45c2-894c-03b731a512fc requested. Cleaning all boards and mplayers.
[01:05:22] [Server thread/WARN]: [FactionWars] Task #119525 for FactionWars v1.9.5.1 generated an exception
java.lang.NullPointerException
	at me.philipsnostrum.factionwars.objects.FactionData.getName(FactionData.java:29) ~[?:?]
	at me.philipsnostrum.factionwars.stats.DatabaseHelper.loadFactionStats(DatabaseHelper.java:57) ~[?:?]
	at me.philipsnostrum.factionwars.objects.FactionData.<init>(FactionData.java:19) ~[?:?]
	at me.philipsnostrum.factionwars.listener.FactionCreateListener$1.run(FactionCreateListener.java:18) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
[01:05:24] [Server thread/INFO]: lueljohn issued server command: /money give CrazyCakeZ 4200
[01:05:26] [Server thread/INFO]: CrazyCakeZ issued server command: /f create RookZ
[01:05:26] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection https://api.mojang.com/users/profiles/minecraft/CrazyCakeZ in main server thread
[01:05:26] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection https://api.mojang.com/users/profiles/minecraft/CrazyCakeZ in main server thread
[01:05:26] [Server thread/WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection https://api.mojang.com/users/profiles/minecraft/CrazyCakeZ in main server thread
[01:05:26] [Server thread/INFO]: [Factions 2.8.2] Non existing factionId a27e4cf7-80b2-403f-b865-32c849ceaa62 requested. Cleaning all boards and mplayers.
[01:05:26] [Server thread/WARN]: [FactionWars] Task #119691 for FactionWars v1.9.5.1 generated an exception
java.lang.NullPointerException
	at me.philipsnostrum.factionwars.objects.FactionData.getName(FactionData.java:29) ~[?:?]
	at me.philipsnostrum.factionwars.stats.DatabaseHelper.loadFactionStats(DatabaseHelper.java:57) ~[?:?]
	at me.philipsnostrum.factionwars.objects.FactionData.<init>(FactionData.java:19) ~[?:?]
	at me.philipsnostrum.factionwars.listener.FactionCreateListener$1.run(FactionCreateListener.java:18) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]

**Comment by creatorfromhell** [comment]
Will look into this, but the pressure should be put on other developers to update as UUIDs are Minecraft's present, and will be Minecraft's future.

**Comment by lueljohn** [comment]
I am using the latest version. I think it's best if you can put a "uuid support=true/false" on the config.
I am using your plugin so much, I can't really find a new one. I'll be pretty dedicated on this plugin. :)

But I hope you'll continue the support after saying I am hosting a cracked server.

**Comment by creatorfromhell** [comment]
Both land claiming, and faction creation are working for me. http://i.imgur.com/7Q9jmL2.png

**Comment by creatorfromhell** [comment]
Created issue to implement the ability to turn off UUID support. https://github.com/TheNewEconomy/TNE-Bukkit/issues/36
