### ISSUE TITLE
Conversion from CraftConomy3 Support

### ISSUE THREAD

**Issue by Aurelien30000** [TheNewEconomy/TNE-Bukkit#361]
#### What feature are you suggesting be added?
Hey !

As you told me on your Discord, I'm here to request the add of CraftConomy3 conversion support.

- As storage, this plugins uses MySql or h2, in my case it's h2.db :
![image](https://user-images.githubusercontent.com/43724816/67378329-60817e00-f587-11e9-97f7-b7aa0e7fec56.png)

- The jar file (for latest version) and bukkit page are here https://dev.bukkit.org/projects/craftconomy/files/2442635

I hope that you will be able to support this plugins, I would be grateful :)

Thanks in advance

#### Expected use-case for said feature?

Similar to the other plugins. Be able to convert CraftConomy3's money into TNE's.

#### Why should this feature be added to TNE?

It's annoyings to reset players' money or to convert manually more of 1000 players xD It's always interesting to support a maximum of plugins for users but also for your plugin's notoriety ;)

**Comment by eyebrawl123** [comment]
hi can you please support craftconomy3 conversion again. I tried to convert the data of craftconomy with tne in 2018 but unfortunately it did not work out at the time and now there is nothing left to support Craftconomy.
please implement that again

**Comment by creatorfromhell** [comment]
This is currently being worked on.

**Comment by creatorfromhell** [comment]
[Conversion-0.0.1.4.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/3806987/Conversion-0.0.1.4.zip)
Please try this conversion module. /convert craftconomy, remember to keep the CraftConomy config.yml in plugins/CraftConomy3/

**Comment by Aurelien30000** [comment]
Hey ! :)

Thank you for that, but an issue persits, here is the entire stack-trace :

> [18:07:15 INFO]: Aurelien30000 issued server command: /convert CraftConomy
[18:07:15 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 34
org.javalite.activejdbc.InitException: Failed to connect to JDBC URL: jdbc:h2:database.db;mode=MySQL;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO
        at org.javalite.activejdbc.DB.open(DB.java:115) ~[?:?]
        at org.javalite.activejdbc.DB.open(DB.java:90) ~[?:?]
        at net.tnemc.conversion.Converter.initialize(Converter.java:45) ~[?:?]
        at net.tnemc.conversion.impl.CraftConomy.h2(CraftConomy.java:73) ~[?:?]
        at net.tnemc.conversion.Converter.convert(Converter.java:152) ~[?:?]
        at net.tnemc.conversion.command.ConvertCommand.lambda$execute$1(ConvertCommand.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-638]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-638]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-638]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: org.h2.jdbc.JdbcSQLException: Un chemin de fichier implicitement relatif au répertoire de travail actuel nest pas autorisé dans lURL de la base de données "jdbc:h2:database.db;mode=MySQL;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO". Utilisez un chemin absolu, ~ /nom, ./nom ou le paramètre baseDir à la place.
A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:database.db;mode=MySQL;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:179) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:155) ~[?:?]
        at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:388) ~[?:?]
        at org.h2.engine.Engine.openSession(Engine.java:50) ~[?:?]
        at org.h2.engine.Engine.openSession(Engine.java:179) ~[?:?]
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157) ~[?:?]
        at org.h2.engine.Engine.createSession(Engine.java:140) ~[?:?]
        at org.h2.engine.Engine.createSession(Engine.java:28) ~[?:?]
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351) ~[?:?]
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124) ~[?:?]
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103) ~[?:?]
        at org.h2.Driver.connect(Driver.java:69) ~[?:?]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_231]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_231]
        at org.javalite.activejdbc.DB.open(DB.java:109) ~[?:?]
        ... 11 more

**Comment by creatorfromhell** [comment]
> Hey ! :)
> 
> Thank you for that, but an issue persits, here is the entire stack-trace :
> 
> > [18:07:15 INFO]: Aurelien30000 issued server command: /convert CraftConomy
> > [18:07:15 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 34
> > org.javalite.activejdbc.InitException: Failed to connect to JDBC URL: jdbc:h2:database.db;mode=MySQL;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO
> > at org.javalite.activejdbc.DB.open(DB.java:115) ~[?:?]
> > at org.javalite.activejdbc.DB.open(DB.java:90) ~[?:?]
> > at net.tnemc.conversion.Converter.initialize(Converter.java:45) ~[?:?]
> > at net.tnemc.conversion.impl.CraftConomy.h2(CraftConomy.java:73) ~[?:?]
> > at net.tnemc.conversion.Converter.convert(Converter.java:152) ~[?:?]
> > at net.tnemc.conversion.command.ConvertCommand.lambda$execute$1(ConvertCommand.java:62) ~[?:?]
> > at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-638]
> > at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-638]
> > at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-638]
> > at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
> > at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
> > at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
> > Caused by: org.h2.jdbc.JdbcSQLException: Un chemin de fichier implicitement relatif au répertoire de travail actuel nest pas autorisé dans lURL de la base de données "jdbc:h2:database.db;mode=MySQL;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO". Utilisez un chemin absolu, ~ /nom, ./nom ou le paramètre baseDir à la place.
> > A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:database.db;mode=MySQL;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-197]
> > at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[?:?]
> > at org.h2.message.DbException.get(DbException.java:179) ~[?:?]
> > at org.h2.message.DbException.get(DbException.java:155) ~[?:?]
> > at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:388) ~[?:?]
> > at org.h2.engine.Engine.openSession(Engine.java:50) ~[?:?]
> > at org.h2.engine.Engine.openSession(Engine.java:179) ~[?:?]
> > at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157) ~[?:?]
> > at org.h2.engine.Engine.createSession(Engine.java:140) ~[?:?]
> > at org.h2.engine.Engine.createSession(Engine.java:28) ~[?:?]
> > at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351) ~[?:?]
> > at org.h2.jdbc.JdbcConnection.(JdbcConnection.java:124) ~[?:?]
> > at org.h2.jdbc.JdbcConnection.(JdbcConnection.java:103) ~[?:?]
> > at org.h2.Driver.connect(Driver.java:69) ~[?:?]
> > at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_231]
> > at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_231]
> > at org.javalite.activejdbc.DB.open(DB.java:109) ~[?:?]
> > ... 11 more

What file is your craftconomy config.yml in? plugins/CraftConomy3 or...?

**Comment by Aurelien30000** [comment]
> /plugins/Craftconomy3/config.yml

**Comment by creatorfromhell** [comment]
I think I know what caused this, try this one.
[Conversion-0.0.1.4.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/3825071/Conversion-0.0.1.4.zip)

**Comment by Aurelien30000** [comment]
Thanks but I'm sorry, I still encounter exactly the same stacktrace :x

**Comment by Aurelien30000** [comment]
And if you need more details, don't hesitate ;)

**Comment by creatorfromhell** [comment]
> And if you need more details, don't hesitate ;)

Just post the new stacktrace

**Comment by creatorfromhell** [comment]
Forget the above, I modified the wrong line xD Try this one
[Conversion-0.0.1.4.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/3826942/Conversion-0.0.1.4.zip)

**Comment by Aurelien30000** [comment]
Still same error :x
I also have the impression that the jar file size hasn't changed.

> [11:29:45 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 29
org.javalite.activejdbc.InitException: Failed to connect to JDBC URL: jdbc:h2:database.h2.db;mode=MySQL;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO
        at org.javalite.activejdbc.DB.open(DB.java:115) ~[?:?]
        at org.javalite.activejdbc.DB.open(DB.java:90) ~[?:?]
        at net.tnemc.conversion.Converter.initialize(Converter.java:45) ~[?:?]
        at net.tnemc.conversion.impl.CraftConomy.h2(CraftConomy.java:73) ~[?:?]
        at net.tnemc.conversion.Converter.convert(Converter.java:152) ~[?:?]
        at net.tnemc.conversion.command.ConvertCommand.lambda$execute$1(ConvertCommand.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-638]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-638]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-638]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: org.h2.jdbc.JdbcSQLException: Un chemin de fichier implicitement relatif au répertoire de travail actuel nest pas autorisé dans lURL de la base de données "jdbc:h2:database.h2.db;mode=MySQL;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO". Utilisez un chemin absolu, ~ /nom, ./nom ou le paramètre baseDir à la place.
A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:database.h2.db;mode=MySQL;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:179) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:155) ~[?:?]
        at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:388) ~[?:?]
        at org.h2.engine.Engine.openSession(Engine.java:50) ~[?:?]
        at org.h2.engine.Engine.openSession(Engine.java:179) ~[?:?]
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157) ~[?:?]
        at org.h2.engine.Engine.createSession(Engine.java:140) ~[?:?]
        at org.h2.engine.Engine.createSession(Engine.java:28) ~[?:?]
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351) ~[?:?]
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124) ~[?:?]
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103) ~[?:?]
        at org.h2.Driver.connect(Driver.java:69) ~[?:?]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_231]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_231]
        at org.javalite.activejdbc.DB.open(DB.java:109) ~[?:?]
        ... 11 more

**Comment by creatorfromhell** [comment]
[Conversion-0.0.1.4.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/3827386/Conversion-0.0.1.4.zip)
try this one now

**Comment by Aurelien30000** [comment]
No error this time, but "extracted.yml" file is empty and no data has been really converted :)

Here is the logs : 

> > convert CraftConomy
[16:35:14 INFO]: Conversion is now in progress.
[16:35:15 INFO]: Conversion has completed. Running restoration command.
[16:35:15 INFO]: Restored accounts from extracted.yml.

The empty files : 

![image](https://user-images.githubusercontent.com/43724816/68531163-ac664e00-030f-11ea-87b3-87136d868682.png)

If I run for example /money Aurelien30000 (a player who was registered in CraftConomy) and after the conversion command : 

![image](https://user-images.githubusercontent.com/43724816/68531204-36161b80-0310-11ea-84e9-ef988943dceb.png)

Result with TNE : 

![image](https://user-images.githubusercontent.com/43724816/68531212-4fb76300-0310-11ea-9c74-06688c922db7.png)

Info : Also, /money top doesn't show any player except server account.

Thanks in advance :) and sorry  for being so annoying with this plugin :c

**Comment by Aurelien30000** [comment]
Humm, I don't know if it could be the cause of the bug, but database file is named "database.h2.db" and not as you written it here (https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/TNEConversion/src/net/tnemc/conversion/impl/CraftConomy.java#L76)

**Comment by creatorfromhell** [comment]
I changed it locally

**Comment by Aurelien30000** [comment]
Okay, but no data is still really converted (previous message) :x

**Comment by creatorfromhell** [comment]
Yeah i read that, this will have to qait until i have enough time from work and school to install craftconomy and get some data and config files to test with

**Comment by Aurelien30000** [comment]
No problem, but I can help you on this point if you want, give you a database and a configuration file, it will save you some work :)

**Comment by creatorfromhell** [comment]
Certainly, if youre on the discord server just dm them to me and ill check them when i get home from work
