### ISSUE TITLE
TheNewEconomy v0.1.1.9 generated an exception while executing task 24170

### ISSUE THREAD

**Issue by erDUKE21** [TheNewEconomy/TNE-Bukkit#366]
>.... [22:59:43 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 24170
java.lang.NullPointerException: null
at net.tnemc.core.commands.money.MoneyGiveCommand.lambda$execute$0(MoneyGiveCommand.java:75) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-236]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-236]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

I really don't know why it happens, i just see it in console sometimes

TheNewEconomy v0.1.1.9

I only use the last version on spigot

I'm running paper 236

https://paste.ubuntu.com/p/3VwPMgyR74/

**Comment by creatorfromhell** [comment]
This isnt the correct format.
