### ISSUE TITLE
Signs does not work

### ISSUE THREAD

**Issue by Polsaker** [TheNewEconomy/TNE-Bukkit#369]
#### What is the issue/bug you're experiencing?
When I try to create a shop with Signs, nothing happens

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
On a freshly setup Spigot server (git-Spigot-492a779-83af86d (MC: 1.15.1)):
1. Place a sign and write [item] on the first line
2. A stack trace appears on the server console:

```
[13:46:35] [Craft Scheduler Thread - 1/WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 40
java.lang.NullPointerException: null
        at net.tnemc.signs.signs.impl.ItemSign.onSignCreate(ItemSign.java:137) ~[?:?]
        at net.tnemc.signs.signs.SignType.create(SignType.java:111) ~[?:?]
        at net.tnemc.signs.listeners.BlockListener.lambda$onChange$2(BlockListener.java:133) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-492a779-83af86d]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-492a779-83af86d]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

#### TNE version?(exact version number), and whether or not you've made modification to it.
v1.1.9.2, unmodified

#### TNE build?(/tne build), and whether or not you've made modification to it.
TNE build 2Beta119

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.

1. Signs-0.0.1.3, unmodified
2. Mobs-0.1.3.0, unmodified

#### Spigot/Bukkit version?

git-Spigot-492a779-83af86d (MC: 1.15.1)

#### config.yml

Default, unmodified config file

**Comment by creatorfromhell** [comment]
I'm going to push this one into the Signs Rewrite ticket. Since the rewrite will happen this week or next.
