### ISSUE TITLE
Can't use /money note -args command

### ISSUE THREAD

**Issue by Ant4rez** [TheNewEconomy/TNE-Bukkit#370]
**What is the issue/bug you're experiencing?**

I can't use the comand /money note amount currency, because generated and exception while executing task 163.

**How can the issue be reproduced?(i.e. the steps to make the issue occur again)**

Just type the command for example: /money note 350 usd

**TNE version?**
0.1.19

**TNE build?**
2Beta119

**Modules Loaded?**
None

**Spigot/Bukkit version?**
Paper version git-Paper-237 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Is your server run in online mode?**
No, it is false mode.

**The exact command you ran w/ arguments?**
/money note 100 rupias

**config.yml?**
https://paste.ubuntu.com/p/G6DnpJZy9X/

**Your latest server log file?**
https://paste.ubuntu.com/p/2PRZ5zRZFg/

**Comment by creatorfromhell** [comment]
Quick question, if you set your minimum to 5.00, does it correct this issue?

**Comment by Ant4rez** [comment]
> Quick question, if you set your minimum to 5.00, does it correct this issue?

On which setting you want me to change it to 5.00?

**Comment by creatorfromhell** [comment]
In your currency's yaml file, minimum under the note section

**Comment by Ant4rez** [comment]
I change it and try it again but i get this error:

`[14:52:15 INFO]: Ant4rez issued server command: /money note 50 rupia
[14:52:15 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 46
java.lang.NullPointerException: null
        at net.tnemc.core.commands.money.MoneyNoteCommand.lambda$execute$1(MoneyNoteCommand.java:106) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by creatorfromhell** [comment]
What does /cur list show?

**Comment by Ant4rez** [comment]
Show that the currency's for the world called world is rupia.

**Comment by creatorfromhell** [comment]
> Show that the currency's for the world called world is rupia.

Screenshot.

**Comment by creatorfromhell** [comment]
Also, zip and post your currencies directory.

**Comment by Ant4rez** [comment]
![1](https://user-images.githubusercontent.com/25251234/71634456-06daa700-2bfb-11ea-8836-6ea3fde154fa.png)

[currencies.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/4013524/currencies.zip)

**Comment by creatorfromhell** [comment]
> ![1](https://user-images.githubusercontent.com/25251234/71634456-06daa700-2bfb-11ea-8836-6ea3fde154fa.png)
> 
> [currencies.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/4013524/currencies.zip)

And what happens if you type /money note 50 Rupia?

**Comment by Ant4rez** [comment]
> > ![1](https://user-images.githubusercontent.com/25251234/71634456-06daa700-2bfb-11ea-8836-6ea3fde154fa.png)
> > [currencies.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/4013524/currencies.zip)
> 
> And what happens if you type /money note 50 Rupia?

This:

`[18:35:38 INFO]: Ant4rez issued server command: /money note 50 rupia
[18:35:38 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 38
java.lang.NullPointerException: null
        at net.tnemc.core.commands.money.MoneyNoteCommand.lambda$execute$1(MoneyNoteCommand.java:106) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by Ant4rez** [comment]
And if i wrote the word "Rupia" with uppercase R happen this:
`[18:36:18 INFO]: Ant4rez issued server command: /money note 50 Rupia
[18:36:18 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 39
java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]:
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:49) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.NamespacedKey.minecraft(NamespacedKey.java:142) ~[patched_1.14.4.jar:git-Paper-237]
        at net.tnemc.core.common.currency.CurrencyNote.lambda$build$0(CurrencyNote.java:90) ~[?:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_231]
        at net.tnemc.core.common.currency.CurrencyNote.build(CurrencyNote.java:89) ~[?:?]
        at net.tnemc.core.common.CurrencyManager.createNote(CurrencyManager.java:274) ~[?:?]
        at net.tnemc.core.commands.money.MoneyNoteCommand.lambda$execute$1(MoneyNoteCommand.java:135) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by creatorfromhell** [comment]
and since this is presumably your default currency, what happens when you just type /money note 50?

**Comment by Ant4rez** [comment]
This:

`[18:38:18 INFO]: Ant4rez issued server command: /money note 50
[18:38:18 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 40
java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]:
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:49) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.NamespacedKey.minecraft(NamespacedKey.java:142) ~[patched_1.14.4.jar:git-Paper-237]
        at net.tnemc.core.common.currency.CurrencyNote.lambda$build$0(CurrencyNote.java:90) ~[?:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_231]
        at net.tnemc.core.common.currency.CurrencyNote.build(CurrencyNote.java:89) ~[?:?]
        at net.tnemc.core.common.CurrencyManager.createNote(CurrencyManager.java:274) ~[?:?]
        at net.tnemc.core.commands.money.MoneyNoteCommand.lambda$execute$1(MoneyNoteCommand.java:135) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by creatorfromhell** [comment]
Try removing the following from Rupia.yml and restarting then retrying.

```


    #All configurations relating to enchantment identification for the note item
    #The format is - enchantment name
    #Optional.
    Enchantments:
    - ""

    #All configurations relating to item flags identification for the note item
    #The format is - item flag
    #Optional.
    Flags:
    - ""
```

**Comment by Ant4rez** [comment]
Now if i type /money note 50, the plugin doesn't give an error but tell you that the transaction can't be done in this moment, and if i wrote /money note 50 rupia, i get this:

`[18:45:44 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 43
java.lang.NullPointerException: null
        at net.tnemc.core.commands.money.MoneyNoteCommand.lambda$execute$1(MoneyNoteCommand.java:106) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by creatorfromhell** [comment]
Removing Rupia was on purpose, it'll still throw an exception, yes. Post your updated Rupia.yml.

**Comment by Ant4rez** [comment]
[Rupia.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/4013552/Rupia.zip)

**Comment by creatorfromhell** [comment]
Alright, I'll have to run further tests locally to get better information. Is your default world in your server.properties "world"?

**Comment by Ant4rez** [comment]
> Alright, I'll have to run further tests locally to get better information. Is your default world in your server.properties "world"?

Yes. my default world is called world and that name is on the server.properties file

**Comment by creatorfromhell** [comment]
http://prntscr.com/qi3x7c is my results from testing. Could you try changing your default world value( https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/TNE/src/net/tnemc/resources/config.yml#L17) in config.yml to TNE_SYSTEM.

**Comment by Ant4rez** [comment]
Now works https://prnt.sc/qi6agb.

**Comment by creatorfromhell** [comment]
https://cdn.discordapp.com/attachments/267902896970924036/662862049159938067/TNE-1.1.9.2.jar should fix this issue when the default world setting is not TNE_SYSTEM
