### ISSUE TITLE
tne.money.* is already defined

### ISSUE THREAD

**Issue by hugo4715** [TheNewEconomy/TNE-Bukkit#405]
#### What is the issue/bug you're experiencing?
I have an error on startup with the default configuration and no other plugins installed.
` tne.money.* is already defined`
https://pastebin.com/Kp6P77Qv
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Launch a spigot 1.8.8 server and install TNE.

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9 default config and no modifications
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119b
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
none, default 
#### Spigot/Bukkit version?
[22:53:45 INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
#### Is your server run in online mode?
Both give the same error
#### The exact command you ran w/ arguments?
Does not apply
#### config.yml?
Default config https://paste.ubuntu.com/p/sW3H86MQsj/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/B4CNy32QfT/

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by hugo4715** [comment]
Still hapening 😢 
https://sentry.io/share/issue/2ffd408f77bf419d8aeeeaa24f28e057/

**Comment by creatorfromhell** [comment]
Should be corrected in the beta build.

**Comment by hugo4715** [comment]
The bug is still present in version 0.1.1.12

**Comment by creatorfromhell** [comment]
Tried reproducing this locally, unable to.

**Comment by Futodama** [comment]
[12:29:14 ERROR]: Error occurred while enabling TheNewEconomy v0.1.1.9 (Is it up to date?)
java.lang.IllegalArgumentException: The permission tne.money.give.* is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:724) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:716) ~[patched_1.16.5.jar:git-Paper-639]
	at net.tnemc.core.common.CurrencyManager.initPermissions(CurrencyManager.java:83) ~[?:?]
	at net.tnemc.core.common.CurrencyManager.(CurrencyManager.java:69) ~[?:?]
	at net.tnemc.core.common.EconomyManager.(EconomyManager.java:66) ~[?:?]
	at net.tnemc.core.TNE.onEnable(TNE.java:348) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-639]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:391) ~[?:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2171) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1986) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1939) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-639]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
[12:29:14 INFO]: [TheNewEconomy] Disabling TheNewEconomy v0.1.1.9
[12:29:14 ERROR]: Error occurred while disabling TheNewEconomy v0.1.1.9 (Is it up to date?)
java.lang.NullPointerException: null
	at net.tnemc.core.TNE.onDisable(TNE.java:531) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-639]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:391) ~[?:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-639]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2171) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1986) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1939) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-639]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-639]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
	
	Самое смешное, что плагин работает, хоть и числится выключенным.

**Comment by Futodama** [comment]
Просто ошибка из той-же серии, что и tne.money.* is already defined
