### ISSUE TITLE
error while enabling tne 0.1.1.9 1.15 spigot

### ISSUE THREAD

**Issue by 32Vache** [TheNewEconomy/TNE-Bukkit#415]
error occurred while enabling theneweconomy v0.1.1.9 (is it up to date?) java.lang.numberformatexception: for input string: "1 "
occurs when server tries enabling tne, plugin still starts but any tne command returns An internal error has occurred when attempting to perform this command

**Comment by 32Vache** [comment]
`[15:05:53] [Server thread/INFO]: [TheNewEconomy] Enabling TheNewEconomy v0.1.1.9
[15:05:53] [Server thread/INFO]: Loading Configurations.
[15:05:53] [Server thread/INFO]: Initializing Configurations.
[15:05:53] [Server thread/INFO]: Error while trying to load: config.yml
[15:05:53] [Server thread/INFO]: Please let a professional know about the following:
[15:05:53] [Server thread/INFO]: ------------------- TNE Error Log -------------------
[15:05:53] [Server thread/WARN]: net.tnemc.config.CommentedConfiguration.decodeNodes(CommentedConfiguration.java:140)
[15:05:53] [Server thread/WARN]: net.tnemc.config.CommentedConfiguration.load(CommentedConfiguration.java:195)
[15:05:53] [Server thread/WARN]: net.tnemc.config.CommentedConfiguration.load(CommentedConfiguration.java:155)
[15:05:53] [Server thread/WARN]: net.tnemc.config.CommentedConfiguration.load(CommentedConfiguration.java:122)
[15:05:53] [Server thread/WARN]: net.tnemc.core.TNE.initializeConfiguration(TNE.java:902)
[15:05:53] [Server thread/WARN]: net.tnemc.core.TNE.initializeConfigurations(TNE.java:854)
[15:05:53] [Server thread/WARN]: net.tnemc.core.TNE.initializeConfigurations(TNE.java:839)
[15:05:53] [Server thread/WARN]: net.tnemc.core.TNE.loadConfigurations(TNE.java:822)
[15:05:53] [Server thread/WARN]: net.tnemc.core.TNE.onEnable(TNE.java:234)
[15:05:53] [Server thread/WARN]: org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:05:53] [Server thread/WARN]: org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[15:05:53] [Server thread/WARN]: org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[15:05:53] [Server thread/WARN]: org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
[15:05:53] [Server thread/WARN]: org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
[15:05:53] [Server thread/WARN]: net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[15:05:53] [Server thread/WARN]: net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
[15:05:53] [Server thread/WARN]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[15:05:53] [Server thread/WARN]: java.lang.Thread.run(Unknown Source)
[15:05:53] [Server thread/INFO]: ----------------- End of Error Log -----------------`
[...]
`[15:05:54] [Server thread/ERROR]: Error occurred while enabling TheNewEconomy v0.1.1.9 (Is it up to date?)
java.lang.NumberFormatException: For input string: "1   "
    at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_241]
    at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_241]
    at java.math.BigInteger.<init>(Unknown Source) ~[?:1.8.0_241]
    at java.math.BigInteger.<init>(Unknown Source) ~[?:1.8.0_241]
    at net.tnemc.core.common.currency.loader.BasicCurrencyLoader.loadTiers(BasicCurrencyLoader.java:141) ~[?:?]
    at net.tnemc.core.common.currency.loader.BasicCurrencyLoader.loadCurrencies(BasicCurrencyLoader.java:107) ~[?:?]
    at net.tnemc.core.common.CurrencyManager.loadCurrencies(CurrencyManager.java:114) ~[?:?]
    at net.tnemc.core.TNE.onEnable(TNE.java:349) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-2040c4c-893ad93]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot.jar:git-Spigot-2040c4c-893ad93]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot.jar:git-Spigot-2040c4c-893ad93]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot.jar:git-Spigot-2040c4c-893ad93]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot.jar:git-Spigot-2040c4c-893ad93]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot.jar:git-Spigot-2040c4c-893ad93]
    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot.jar:git-Spigot-2040c4c-893ad93]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot.jar:git-Spigot-2040c4c-893ad93]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

**Comment by creatorfromhell** [comment]
please follow the format. It's an issue with your config.yml formatting, but you didn't follow the format so I can't see what's in your config.yml
