### ISSUE TITLE
Buffered payment thread shutdown Error

### ISSUE THREAD

**Issue by notbike** [TheNewEconomy/TNE-Bukkit#431]
#### What is the issue/bug you're experiencing?

I'm using a popular plugin "Jobs Reborn", but some jobs are not receiving money. For example, Miner (a job) was suppose to get paid per block broken, instead of money I receive this error in my console:

[19:50:02] [Jobs-BufferedPaymentThread/WARN]: java.lang.NullPointerException
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.IDFinder.getID(IDFinder.java:139)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.TNEAPI.hasAccount(TNEAPI.java:182)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.Economy_TheNewEconomy.hasAccount(Economy_TheNewEconomy.java:67)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.Economy_TheNewEconomy.depositPlayer(Economy_TheNewEconomy.java:188)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at net.tnemc.core.common.api.Economy_TheNewEconomy.depositPlayer(Economy_TheNewEconomy.java:182)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.VaultEconomy.depositPlayer(VaultEconomy.java:32)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:158)
[19:50:02] [Jobs-BufferedPaymentThread/WARN]: 	at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)
[19:50:02] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Exception in BufferedPaymentThread, stopping economy payments!
[19:50:02] [Jobs-BufferedPaymentThread/INFO]: [Jobs] Buffered payment thread shutdown.

https://paste.ubuntu.com/p/bYy6bwXZNB/
for easy visibility
-------------
I submit the error to the author of the Jobs Reborn, he told me that this is TNE's issue, not Jobs'.
so here I am begging for help.

big fan of the plugin by the way.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)

Install the plugin
instal TNE
start server
join Miner (not all jobs are affected)
break blocks
error appears

#### TNE version?(exact version number), and whether or not you've made modification to it.

TNE ver. 1.1.9.3. When i type /tne version it says ver 0.1.1.9, no modification

#### TNE build?(/tne build), and whether or not you've made modification to it.

0.1.1.9d no modification

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.

no modules

#### Spigot/Bukkit version?

paper-110, MC ver-1.16.1

#### Is your server run in online mode?

yes

#### The exact command you ran w/ arguments?

not relevant

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)

https://paste.ubuntu.com/p/sFXSnHDmyW/

#### Your latest server log file?(use http://paste.ubuntu.com)

https://paste.ubuntu.com/p/yGXFBCvj3B/

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

I have no idea if it has to do with these configurations

**Comment by suneettipirneni** [comment]
+1 I’ve been getting a lot of NPE’s with the IDFinder, in towny as well.

**Comment by creatorfromhell** [comment]
Please enable debug mode and provide me with the log with debug enabled

**Comment by notbike** [comment]
hi, this is my log with TNE debug mode enabled.

https://paste.ubuntu.com/p/rdNYBfS3MR/

thank you for the help, I appreciate it!

**Comment by creatorfromhell** [comment]
> @creatorfromhell hi, this is my log with TNE debug mode enabled.
> 
> https://paste.ubuntu.com/p/rdNYBfS3MR/
> 
> thank you for the help, I appreciate it!

The log linked doesn't have debug enabled for the error?

**Comment by notbike** [comment]
oh really? Is there an ETA?

**Comment by creatorfromhell** [comment]
> oh really? Is there an ETA?

Not currently, I'm redoing the library to be platform agnostic so it'll take a little longer to piece things together to work for multiple platforms.

**Comment by creatorfromhell** [comment]
[TNE-1.1.9.3-shaded.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/5011411/TNE-1.1.9.3-shaded.zip)
try this it fixed the same issue for another user
