### ISSUE TITLE
[BUG]: 1.18 Material Error

### ISSUE THREAD

**Issue by nfacha** [TheNewEconomy/TNE-Bukkit#487]
### TNE Version

0.1.1.14

### Spigot Version

1.18

### Your config.yml

Not Relevant (Freshly generated and unchanged)

### Your latest server log

Not Relevant

### What part of TNE is the bug affecting?

Won't Startup

### Is your server using online mode?

Yes

### Bug description

Unable to load up TNE on Spigot 1.18, due to material changes.

After  the server starts this error starts spamming after a bit and the plugin commands don't work as expected

```java
[14:13:28] [Server thread/INFO]: Done (83.258s)! For help, type "help"
[14:13:28] [Server thread/INFO]: Timings Reset
[14:13:28] [Craft Scheduler Thread - 7 - TheNewEconomy/WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.13 generated an exception while executing task 75
java.lang.IllegalArgumentException: Material cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:86) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:74) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
	at net.tnemc.core.compatibility.item.ItemCompatibility12.build(ItemCompatibility12.java:29) ~[TNE.jar:?]
	at net.tnemc.core.menu.MenuManager.<init>(MenuManager.java:41) ~[TNE.jar:?]
	at net.tnemc.core.TNE.lambda$initializeConfigurations$24(TNE.java:815) ~[TNE.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-36]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.jar:git-Paper-36]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.jar:git-Paper-36]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

A PR fixing this issue will follow shortly

### How to reproduce

Try to load TNE on Spigot 1.18 and check the startup log

**Comment by creatorfromhell** [comment]
Fixed in https://github.com/TheNewEconomy/TNE-Bukkit/commit/c750bd6a910256b856c68028e6fe02cdd1892647 .
