### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Carisus** [TheNewEconomy/TNE-Bukkit#68]
I keep getting this error when TNE autosaves.

`
[19:27:33 INFO]: [TheNewEconomy] Data saved!
[19:27:33 WARN]: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[19:27:33 WARN]:        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:25)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.UserCache.a(UserCache.java:90)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.UserCache.getProfile(UserCache.java:157)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.Village.b(Village.java:444)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.PersistentVillage.b(SourceFile:228)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.PersistentCollection.a(PersistentCollection.java:97)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.PersistentCollection.a(PersistentCollection.java:82)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1071)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.save(WorldServer.java:1013)
[19:27:33 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.save(CraftWorld.java:744)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:693)
[19:27:33 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[19:27:33 WARN]:        at java.lang.Thread.run(Thread.java:745)`

It isn't there if I remove the plugin.

**Comment by creatorfromhell** [comment]
Is that the full error? If so I don't see anything relating it to TNE.

**Comment by Carisus** [comment]
Yep. Full error. Only gives it if TNE is installed though. I am removing all plugins from the server except TNE to see if it is a conflict somewhere. I have no idea what it could be.

**Comment by creatorfromhell** [comment]
Are you running in offline mode? That seems to be the issue from what I've gathered here: https://bugs.mojang.com/browse/MC-50221.

**Comment by Carisus** [comment]
We are in offline mode, but that is required when running a Bungeecord server. Bungee takes care of the authentication and passes it on to Spigot. Plugins shouldn't notice anything.

**Comment by creatorfromhell** [comment]
Which is why I'm not really sure what I could do as a workaround. The issue is whichever is doing it is passing an all blank user name to the Mojang API, which is strange on its own.

**Comment by Carisus** [comment]
Good news and bad news. Good news is I removed every plugin, including TNE, and the same error was thrown. So it isn't your plugin causing it. The bad news is I removed every plugin from the server and it is still getting thrown from some where I have no idea.  Thanks for your help.

**Comment by creatorfromhell** [comment]
No problem, but as stated in that link I posted it happens when the Mojang API is sent a blank username, because obviously you need a username to get a UUID.
