### ISSUE TITLE
ChestShop not working ?

### ISSUE THREAD

**Issue by Oruss7** [TheNewEconomy/TNE-Bukkit#78]
Nothing happen when buy/sell to ChestShop sign. 

Vault 1.5.6-b49
ChestShop version 4.0-r5

**Comment by Oruss7** [comment]
```
[20:39:51] [Server thread/ERROR]: Could not pass event PreTransactionEvent to ChestShop v4.0-r5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:104) [ChestShop4.0-r5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7745d45-02d704b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-7745d45-02d704b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at com.Acrobot.ChestShop.Listeners.AuthMeChestShopListener.onPreTransaction(AuthMeChestShopListener.java:25) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	... 26 more
[20:39:52] [Server thread/ERROR]: Could not pass event CurrencyCheckEvent to ChestShop v4.0-r5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:322) [ChestShop4.0-r5.jar:?]
	at com.Acrobot.ChestShop.Listeners.PreTransaction.PartialTransactionModule.onPreBuyTransaction(PartialTransactionModule.java:50) [ChestShop4.0-r5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:104) [ChestShop4.0-r5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7745d45-02d704b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-7745d45-02d704b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.utils.MISCUtils.getID(MISCUtils.java:396) ~[?:?]
	at com.github.tnerevival.utils.MISCUtils.distringuishId(MISCUtils.java:317) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.handleInitiator(Transaction.java:40) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.perform(Transaction.java:34) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:148) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:138) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsHas(TNEAPI.java:53) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.has(TNEVaultEconomy.java:377) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Economy.Plugins.VaultListener.onCurrencyCheck(VaultListener.java:81) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	... 36 more
[20:39:52] [Server thread/ERROR]: Could not pass event CurrencyAddEvent to ChestShop v4.0-r5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:322) [ChestShop4.0-r5.jar:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.EconomicModule.onBuyTransaction(EconomicModule.java:28) [ChestShop4.0-r5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:111) [ChestShop4.0-r5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7745d45-02d704b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-7745d45-02d704b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.utils.MISCUtils.getID(MISCUtils.java:396) ~[?:?]
	at com.github.tnerevival.utils.MISCUtils.distringuishId(MISCUtils.java:317) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.handleInitiator(Transaction.java:88) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.perform(Transaction.java:34) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:148) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:138) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsAdd(TNEAPI.java:43) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.depositPlayer(TNEVaultEconomy.java:352) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Economy.Plugins.VaultListener.onCurrencyAdd(VaultListener.java:118) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	... 36 more
[20:39:52] [Server thread/ERROR]: Could not pass event CurrencySubtractEvent to ChestShop v4.0-r5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at com.Acrobot.ChestShop.ChestShop.callEvent(ChestShop.java:322) [ChestShop4.0-r5.jar:?]
	at com.Acrobot.ChestShop.Listeners.PostTransaction.EconomicModule.onBuyTransaction(EconomicModule.java:31) [ChestShop4.0-r5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:111) [ChestShop4.0-r5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7745d45-02d704b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-7745d45-02d704b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at com.github.tnerevival.utils.MISCUtils.getID(MISCUtils.java:396) ~[?:?]
	at com.github.tnerevival.utils.MISCUtils.distringuishId(MISCUtils.java:317) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.handleInitiator(Transaction.java:40) ~[?:?]
	at com.github.tnerevival.core.transaction.Transaction.perform(Transaction.java:34) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:148) ~[?:?]
	at com.github.tnerevival.utils.AccountUtils.transaction(AccountUtils.java:138) ~[?:?]
	at com.github.tnerevival.core.api.TNEAPI.fundsHas(TNEAPI.java:53) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.has(TNEVaultEconomy.java:377) ~[?:?]
	at com.github.tnerevival.core.TNEVaultEconomy.withdrawPlayer(TNEVaultEconomy.java:439) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Economy.Plugins.VaultListener.onCurrencySubtraction(VaultListener.java:129) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7745d45-02d704b]
	... 36 more
```

**Comment by creatorfromhell** [comment]
(unrelated to the error) but if you plan to use external shop plugins make sure to disable shops.

**Comment by creatorfromhell** [comment]
Also, do you have a link to the ChestShop plugin you're using?

**Comment by Eredrim** [comment]
Hello, I works with Oruss7. Our version of chestShop is compiled from the official gitHub https://github.com/Acrobot/ChestShop-3. It corresponds to this https://dev.bukkit.org/bukkit-plugins/chestshop/

**Comment by creatorfromhell** [comment]
Appears to be working fine for me. http://imgur.com/a/ZBnEy

**Comment by Eredrim** [comment]
Maybe you should try with the latest version of Vault (1.5.6) ? It is that one we use on our server. I've seen you use 1.5.3 on your screenshot.

**Comment by creatorfromhell** [comment]
http://imgur.com/a/b4c30 same result, Vault versions don't mean anything anyways, the API is the same.

**Comment by Eredrim** [comment]
I have some news. With the latest version, player can purchase but money is taken from the essentials plugin balance.

Example : I have $100 in my balance account. I buy a cookie for $1. If I type /bal, I have $100 but if I type /ebal (essentials alias), I have $99.
