### ISSUE TITLE
Number parsing problem

### ISSUE THREAD

**Issue by Eredrim** [TheNewEconomy/TNE-Bukkit#84]
When I type /money set playername 10000000, I have a java NumberFormatException. I think you should simply use Long.ParseLong() instead of Integer.ParseInt() to resolve the problem...

**Comment by creatorfromhell** [comment]
Balances use the double datatype. If you could post the error to determine the route cause that'd be greatly appreciated though.

**Comment by Eredrim** [comment]
Oh ! I'm sorry, it is just a memory lapse 😊 
`[23:29:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin TheNewEconomy v0.0.3.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NumberFormatException: For input string: "0E7"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_101]
	at java.lang.Integer.valueOf(Unknown Source) ~[?:1.8.0_101]
	at com.github.tnerevival.utils.MISCUtils.formatBalance(MISCUtils.java:431) ~[?:?]
	at com.github.tnerevival.utils.MISCUtils.formatBalance(MISCUtils.java:425) ~[?:?]
	at com.github.tnerevival.commands.money.MoneySetCommand.execute(MoneySetCommand.java:54) ~[?:?]
	at com.github.tnerevival.commands.TNECommand.execute(TNECommand.java:153) ~[?:?]
	at com.github.tnerevival.commands.money.MoneyCommand.execute(MoneyCommand.java:74) ~[?:?]
	at com.github.tnerevival.TNE.onCommand(TNE.java:164) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
	... 15 more`

**Comment by creatorfromhell** [comment]
Ah, my mistake, long story short, found and fixed.
